version: '3.9'
services:
  racket:
    image: hkim0331/racket
    restart: always
    user: vscode
    # does not work on DockerDesktop nor WSL if enabled
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
