version: '3'

services:
  racket:
    image: hkim0331/racket:0.3
    # restart: always
    user: vscode
    working_dir: /workspace
    volumes:
      - .:/workspace
    entrypoint:
      - sleep
      - infinity
