version: '3.9'
services:
  racket:
    image: hkim0331/racket
    restart: always
    user: vscode
    volumes:
      - ./src:/workspace:cached
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
