version: '3.3'
services:
  racket:
    image: hkim0331/racket
    restart: always
    user: vscode
    # does not work on DockerDesktop nor WSL if enabled
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint:
      - sleep
      - infinity
